[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "recomendador-parcial"
version = "0.1.0"
description = "Sistema recomendador de cursos"

[tool.poetry.dependencies]
python = "^3.9"